### ISSUE TITLE
Running project in Anaconda 3

### ISSUE THREAD

**Issue by Blazer-007** [udacity/ud120-projects#234]
Hi , can anyone tell is it possible  complete projects using Anaconda 3 or python 3.7 because I am getting error at each steps.

**Comment by RileyMShea** [comment]
Strongly recommend doing it in python 2.7.
You can create a python 2.7 environment with conda(installed with anaconda 3)
from terminal in your base environment:
`conda create -n py27 python=2.7 anaconda`
then use that conda environment

Even then you'll probably have errors since the course hasn't been updated in 4 years.  Should be limited to name changes of sklearn modules and some of their default options.

**Comment by nono-london** [comment]
Hi, I am having a lot of troubles converting code into python 3.7. using PyCharm.
1st: I think it is great to have tutorial videos, NEVERTHELESS, as these are teaching tutorial, it should show in big that these are using python2
2nd: Is Google so far behind that they still use, promote, and inter people into using python2??
3rd: what is the logic?, you make us validate easy checkboxes and forget the minimal requirements?

I don't mean to complain, but it feels like having to install some old version which limits you with yother programs unless you have a stupidly high perf computer running multiple envs...

Best and than you!

**Comment by neurosylvia** [comment]
Same here, I will need to change each line of code to be compliant with python 3, although I would really appreciate the authors releasing an updated version.

**Comment by RileyMShea** [comment]
@neurosylvia I completed the course, and I know it's probably not what you want to hear, but I'd just do it in python2.  I wouldn't hold my breath hoping for this repo to be updated anytime in the near future.  I'll also note if you're taking this course through wgu or another university and need to submit the final project I don't if know that they will even accept a python3 submission.

If you want to breeze through this course just setup a `conda` or `virtualenv` environment for python 2.7, and install the exact versions of the packages in the `requirements.txt` of this repo. Then use these sci-kit learn docs [https://scikit-learn.org/0.18/](https://scikit-learn.org/0.18/) since that's the docs for the version of sklearn in the course.

I spent way more time on the course than I should have, trying to make the code work in python 3.  The only major changes between py2 and py3 are:

* some scikit learn package name changes
* print functionality
* pickle implementation

From a learning standpoint, you don't really miss anything from doing the course in python2.

Let me know if you have questions

**Comment by tonycueva** [comment]
@RileyMShea thank you for your advice! I am about to complete the course with python2.7 by creating a `conda` environment.

**Comment by arrickx** [comment]
> @RileyMShea thank you for your advice! I am about to complete the course with python2.7 by creating a `conda` environment.

Hi, I am using sublime text. I also use conda. when I switch to `conda` by `conda create -n py27 python=2.7 anaconda` and `conda activate py27`. it still shows the error such as print error in sublime text. any recommendation?

**Comment by tonycueva** [comment]
> > @RileyMShea thank you for your advice! I am about to complete the course with python2.7 by creating a `conda` environment.
> 
> Hi, I am using sublime text. I also use conda. when I switch to `conda` by `conda create -n py27 python=2.7 anaconda` and `conda activate py27`. it still shows the error such as print error in sublime text. any recommendation?

Hi, did you check if Sublime Text has configured the python path correctly? 

Here is mine in VS Code (settings.json file):

`{
    "python.pythonPath": "/opt/anaconda3/envs/py27/bin/python"
}`

Let me know if it helps

**Comment by trsvchn** [comment]
@Blazer-007 

> Hi , can anyone tell is it possible complete projects using Anaconda 3 or python 3.7 because I am getting error at each steps.

Yes, it is possible I've ported this `ud120` code to `conda` env, `python3.8` and `jupyter`. Feel free to take a look at my fork here [trsvchn/ud120-projects-py3-jupyter](https://github.com/trsvchn/ud120-projects-py3-jupyter).
