### ISSUE TITLE
Was the email content generated or not?

### ISSUE THREAD

**Issue by zippeurfou** [udacity/ud120-projects#7]
Hi,
I have been following the course and I really love it. I was intrigued to look into the original "email content" to see how it was prepossessed. The data really looks legit and even if it has been stemmed you can clearly collect id/pw and email address. Therefore, I was wondering if you actually generated it or if it is actually legit information. If it is legit, I'd advise trying to remove these information as people (sadly) don't often change their username/password.
Best,

**Comment by cmmalone** [comment]
Hi Zippeurfou,

Smart question.  Yes, the email is legit, and there were/are definitely things in there that the senders/recipients probably didn’t want public (for example: http://abcnews.go.com/US/story?id=90221 <http://abcnews.go.com/US/story?id=90221>).  That said, the dataset has been public (and very famous) for over 10 years, and the version that we use has actually been scrubbed of a lot of the most sensitive information.  

If the messages had recently made public, I would agree that a great deal of caution would be appropriate.  However, since it’s been out so long, I think it’s safe to say that any exposed usernames/passwords would have already been changed.

But here’s just something to ponder, though—there’s tens of thousands of messages in the corpus.  What do you think would be an effective way to identify and remove personally identifiable information?  (That category includes data of many formats—usernames and passwords, but also social security numbers, credit card numbers, addresses, etc…).  I ask the question because it’s a tough one, not because I have a simple answer.  But I think that there are companies that make a _lot_ of money scrubbing datasets of PII, and the Enron corpus actually serves as one of the “benchmark” datasets that they can use to demonstrate that their methods work.  Just food for thought.

Katie

**Comment by erip** [comment]
I recommend closing this. It's not an issue - this is a famous dataset.
