### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by cconverge123** [udacity/ud120-projects#96]
Hi, I am currently taking the Intro to ML course and it turns out many files are missing....For example, one file needed gives this error:
 word_data = pickle.load( open(words_file, "r"))

FileNotFoundError: [Errno 2] No such file or directory: '../text_learning/word_data.pkl'
It seems not all necessary files for completing the quizzes are uploaded here on GitHub....
And this is just one example file that is missing...
Please update your documentation if you want people to take the course.
Thank you.

**Comment by ShengKungYi** [comment]
Could you be more specific about which file is generating the error? The closest example I can think of is from `feature_selection/find_signature.py` which has the line

`words_file = "../text_learning/your_word_data.pkl"`

rather than `'../text_learning/word_data.pkl'`. Note that the script also says that `your_word_data.pkl` will be generated from going through the previous mini-project; you will create the file by completing and running the `text_learning/vectorize_text.py` script. If you go through the course and the associated mini-projects in order, you should have all the files that you need to complete the materials. In addition, make sure that your working directory is always the same as the folder that contains the script that you are running so that all of the references are in their expected places.

**Comment by cconverge123** [comment]
I started out with the setup.py which BTW didn't work, so went to the website and downloaded and unzipped all the data files. Then started the Quiz, by completing the code required in nb_author_id.py to calculate the accuracy. The first error encountered when running this one was:

  File "/Users/Desktop/ud120-projects-master/naive_bayes/nb_author_id.py", line 22, in <module>
    features_train, features_test, labels_train, labels_test = preprocess()
  File "../tools/email_preprocess.py", line 38, in preprocess
    authors = pickle.load(authors_file_handler)
TypeError: a bytes-like object is required, not 'str'
so, I started tracing it back to the other files to find out where the problem originated. While doing this, I encountered the error mentioned in the previous message. All this is part of the mini-project which I am completing right now.

**Comment by cconverge123** [comment]
BTW, the reason startup.py didn't work is because of this error which may be due to files being written in an earlier version of Python (I have a more updated version of Python so had to change the command print "..." to print() - this was the only thing highlighted that needed changing. But obviously, my Python does not recognize the module attribute  'urlretrieve' but does recognize url lib

  File "/Users/DrC-GStefanita/Desktop/ud120-projects-master/tools/startup.py", line 35, in <module>
    urllib.urlretrieve(url, filename="../enron_mail_20150507.tgz")

AttributeError: module 'urllib' has no attribute 'urlretrieve'

**Comment by ShengKungYi** [comment]
OK, thanks for the additional information. The course was originally written for Python 2, so you might want to set up an environment with Python 2.7 to work through the courseware for compatibility reasons. As another alternative, I believe that there is a pull request that claims Python 3 compatibility that you might look up. Sorry for any inconvenience on this. Any future revisions to the material will be done with Python 3 in mind to hopefully minimize confusion.
